name: DB Monitor Update

on:
  schedule:
    - cron: '*/5 * * * *' # Alle 5 Minuten
  workflow_dispatch: # Erlaubt manuelles Starten

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ganz wichtig für den Push-Befehl!
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run Update Script
        run: python update_stations.py # Name deiner Python-Datei prüfen!

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Live-Daten Update: $(date +'%d.%m.%Y %H:%M')" || exit 0
          git push
